version: "3.7"

services:
  db:
    container_name: db
    restart: always
    image: postgres
    volumes:
      - ./library_back/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  app:
    container_name: app
    restart: always
    build: ./library_back
    command: >
        sh -c "python manage.py makemigrations
        && python manage.py migrate
        && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./library_back:/backend
    ports:
      - 8000:8000
    depends_on:
      - db
  web:
    container_name: web
    restart: always
    build: ./library_front
    command: npm start
    ports:
      - 3000:3000
    depends_on:
      - app
  nginx:
    container_name: nginx
    restart: always
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./library_front/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
