version: "3.7"

services:
  db:
    container_name: db
    image: postgres
    volumes:
      - ./library_back/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
