name: CD

on:
  workflow_run:
    workflows: CI
    types:
      - completed

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push (backend)
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:library_back"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/trabalho-gces-backend:latest


      - name: Build and Push (frontend)
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:library_front"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/trabalho-gces-frontend:latest
